- filename: StaticIv1.js
  description: Names of a secure and an insecure initialization vector (static) are stored in an object's field by using the Identity function. The secure one is then used to finalize the cipher.
  secure: yes
