- filename: BrokenCrypto1.js
  description: The algo variables are set to an insecure 'des' and a secure cipher 'aes-256-gcm', respectively. But only the insecure one is utilized to initialize the cipher object.
  secure: no