- filename: EcbMode1.js
  description: One path in the conditional creates a cipher with the insecure algorithm aes-256-ecb, while the other one creates a cipher with the secure algorithm aes-256-gcm. Only the aes-256-gcm path is reachable.
  secure: yes
