- filename: BrokenCrypto1.js
  description: One path in the conditional creates a cipher object with the insecure algorithm 'des'; another creates the cipher object with aes-256-gcm which is secure; a third one creates the cipher object with bf-cbc, which is insecure. Only the 'des' path is reachable.
  secure: no
