- filename: Staticlv1.js
  description: Two initialization vectors are intiialized, one statially insecure (iv1) and one randomly secure (iv2). The random, insecure iv is then used to create the cipher.
  secure: no