- filename: BrokenCrypto1.js
  description: Five different variables are set to names of different insecure and secure ciphers. One variable containing a secure algo is then used to initialize the cipher.
  secure: yes
