- filename: pbkdf2Parameters1.js
  description: Two paths in the conditional initializes a random salt; one path creates a static salt. Only a path that initializes a random salt is reachable.
  secure: yes


- filename: pbkdf2Parameters2.js
  description: Two paths in the conditional initialize the number of iterations to 1000000; the other path initializes it to 100, which is insecure. Only a path that initializes it to 1000000 is reachable.
  secure: yes