- filename: BrokenCrypto1.js
  description: One path in the conditional creates a cipher object with the insecure algorithm 'des'; another creates the cipher object with aes-256-gcm which is secure; a third and fourth path create it with rc2 and rc4, which are insecure. Only the 'rc2' path is reachable.
  secure: no
