- filename: BrokenCrypto1.js
  description: One path in the conditional creates a cipher object with the insecure algorithm 'des'; the other creates the cipher object with aes-256-gcm which is secure. Only the 'aes-256-gcm' path is reachable.
  secure: yes
