
- filename: SmallKeySize1.js
  description: Names of a secure and an insecure keysize length (1024) are stored in an object's field by using the Identity function. The insecure one is then used to finalize the keypair.
  secure: no
