- filename: SmallKeySize1.js
  description: Initialized two key sizes, one insecure (1024 too small) and one secure (3072) and proceeded to use the secure keylength to generate the key.
  secure: yes
