- filename: pbkdf2Parameters1.js
  description: Five variables are set to static or dynamically filled byte values. One variable containing a static array is then used as the parameeter in the pbkdf2 function.
  secure: no