- filename: StaticIv1.js
  description: One path in the conditional initializes the iv with random bytes, whereas the other path generates a static iv, which is insecure. Only the path that generates a random iv is reachable.
  secure: yes
