- filename: StaticIv1.js
  description: Two paths in the conditional initializes the iv with random bytes, whereas the other path generates a static iv, which is insecure. Only a path that generates a random iv is reachable, so this code is secure.
  secure: yes
