- filename: BrokenCrypto1.js
  description: The algo members are set to an insecure 'des' and a secure cipher 'aes-256-gcm', respectively. But only the latter one is utilized to initialize the cipher object.
  secure: yes
